name: CloudBees Sample Workflow
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1

on: [workflow_dispatch]

jobs:
  test:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        run: echo "hello world"
