name: CloudBees Sample Workflow
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1

on: [workflow_dispatch]

jobs:
  test:
    steps:
      - name: Say hello
        uses: docker://alpine:latest
        run: |
              echo "Doing some job........"
              sleep 10
